set_appliance_state:
  description: "Sets the state of an appliance"
  fields:
    entity_id:
      {
        description: "Enter the entity_id for the appliance.",
        example: "switch.appliance",
      }
    appliance_state:
      {
        description: "Enter the state, can be True or False.",
        example: True,
      }
set_home_mode:
  description: "Sets the Wiser Smart home mode"
  fields:
    mode:
      {
        description: "Enter the target mode for the system (manual, schedule, energysaver, holiday)",
        example: "manual",
      }
    come_back_time:
      {
        description: "If mode is holiday provide the date for return as a timestamp, else 0",
        example: 123456,
      }
